import { ThemeProvider } from "@/components/ui/theme-provider";
import { cn } from "@/lib/utils";

import { AuthProvider } from "@/lib/AuthProvider";
import { getServerSession } from "next-auth";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const iranSans = localFont({ src: "../fonts/IranianSans.ttf" });

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en" dir="rtl">
      <body
        className={cn(
          "bg-background min-h-screen antialiased",
          iranSans.className
        )}
      >
        <AuthProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
            <Toaster position="top-center" reverseOrder={false} />
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
